### ISSUE TITLE
SDK: self should be renamed

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/emif-fb#870]
The self should be renamed, because it is a convection in javascript. Some external suggestion was: sdk. But new ideas are welcome.

**Comment by ribeiroct** [comment]
There's no alteration needed to be done for this change, except documentation-wise, since the user is the one declaring the variable name. It can call it whatever it wants

    plugin = function(context){
     ...
    } 

would work just the same, without any alteration. I will change all documentation. Do you prefer 'sdk' or 'context' or 'container' ?

**Comment by bastiao** [comment]
context is perfect! change the documentation, please. :+1:
