### ISSUE TITLE
Plugin SDK Dependencies Filename

### ISSUE THREAD

**Issue by tnovo** [bioinformatics-ua/emif-fb#907]
Dependencies are uploaded to

static/files/<hash>/<version>/<hash>_filename.ext

Suggested change to:

static/files/<hash>/<version>/filename.ext

It's easier for developers and since most (if not all) of these dependencies are to be run on client side, hashing the filename is not relevant.

**Comment by ribeiroct** [comment]
- The file names are not hashed, the hash is the revision. 

The view over that urls can't be that simplistic.

 We have a folder for each plugin (with the plugin hash). Then we must have a folder for each revision, because different revisions can use different dependencies. 

Then we keep all files over time we don't replace them. Because this could prove useful, and space ins't really a problem. (we do this on other places like in the fingerprint documents and in the pop. characteristics files).

What we could do, is the possibility to serve the last version of a file through the name, without specifying the hash. The hashing is not random.

**Comment by ribeiroct** [comment]
I added a utility url for the files that doesn't use the real path, but returns the latest revision.

like p.e. 
/developer/plugin_slug/plugin_version/filename

hope it helps. The copy button on the dep manager has been replaced with this link so you can copy them from there too.
