### ISSUE TITLE
Dep manager Zip Archive With directory tree

### ISSUE THREAD

**Issue by tnovo** [bioinformatics-ua/emif-fb#909]
When adding a zip archive dependency with a diretory structure an error arises: 

```IOError at /developer/<hash>/<version>/deps
[Errno 2] No such file or directory: u'./emif/static/files/<hash>/<version>/<hash>_dir/file.ext'```

Suggestions to fix:
1. Allow directory structure ( needs an improvement in the interface to allow it)
2. If there's an error extracting the archive, return an invalid error message to the user

**Comment by ribeiroct** [comment]
Only flat zip archives are supported. At best the correct solution is ignore directories all together when uploading (crashing was not intended).

I discussed at length the problem with @bastiao and we agreed having to implement something like a file system gui to manage dependencies (in a similar way to dropbox online interface) is for now out of scope, because it would take a while and doesn't have much advantages.
It would be also a big point of possible vulnerabilities, since we are actually serving this files, not just keeping them.

Systems that use a big structured layout like Achilles aren't meant to be isolable and portable, but act as a separate app so they have this approach. We can let them.

The best solution to integrate this is using a service apart for it and integrating it in the system. Not having it entirely run from the system. The structured directories won't be your only problem. There's also the backend management of data files that is hard be managed by a generic plugin system, and really shouldn't.

I took a look on how to integrate Achilles Web statically serving Achilles through an apache server, i think @bastiao sent it to you today.

Eventually making an Django App to manage services to the achilles and doing something like my example would be the best solution.
